"""Word list for the 'market' scenario.

Per nanovietnam_spec v0.3 §11 (non-goals): the full ~50-word list is a content task, done by hand,
not generated by code. This file ships a real (not placeholder) starter set large enough to
exercise the whole pipeline; extend the list by hand up to ~50 before real daily use.
"""

from __future__ import annotations

from dataclasses import dataclass


@dataclass(frozen=True)
class WordCard:
    word: str
    translit: str
    gloss: str
    tone: str


MARKET_WORDS: list[WordCard] = [
    WordCard("xin chào", "sin chaò", "здравствуйте", "flat"),
    WordCard("cảm ơn", "кам эн", "спасибо", "falling"),
    WordCard("bao nhiêu", "бао ньеу", "сколько", "flat"),
    WordCard("đắt", "дат", "дорого", "sharp"),
    WordCard("rẻ", "зэ", "дёшево", "heavy"),
    WordCard("quả", "куа", "фрукт", "heavy"),
    WordCard("rau", "зау", "овощи", "flat"),
    WordCard("cá", "ка", "рыба", "sharp"),
    WordCard("thịt", "тхит", "мясо", "heavy"),
    WordCard("nước", "ныок", "вода", "sharp"),
    WordCard("một", "мот", "один", "heavy"),
    WordCard("hai", "хай", "два", "flat"),
    WordCard("ba", "ба", "три", "flat"),
    WordCard("mua", "муа", "покупать", "flat"),
    WordCard("bán", "бан", "продавать", "sharp"),
    WordCard("chợ", "тё", "рынок", "heavy"),
    WordCard("tiền", "тиен", "деньги", "falling"),
    WordCard("giảm giá", "зям зя", "скидка", "falling-falling"),
    WordCard("ngon", "нгон", "вкусно", "flat"),
    WordCard("cảm ơn nhiều", "кам эн ньеу", "большое спасибо", "falling-flat"),
]
